# Site settings
title: Lessons
email: eyeversuseye@gmail.com
description: Open source collections of lessons learned.
baseurl: "/lessons" # the subpath of your site, e.g. /blog/
url: "yratof.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:title/
twitter_username: yratof
github_username:  yratof
timezone: Europe/Oslo

# Extra things
exclude: ['node_modules']

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap